development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tasklist_development
  pool: 5
  username: root
  password: ""
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tasklist_test
  pool: 5
  username: root
  password: ""
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tasklist
  pool: 5
  username: root
  password: ""
  host: localhost
  port: 3306

